config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users do
    resources :photos do
      resources :tags
      resources :favorites
    end
  end
  root :to => 'users#show'
  resources :sessions
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :photos
  belongs_to :users
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :description, presence: :true

  has_many :tags
  has_many :users, through: :tags

  has_many :favorites
  has_many :users, through: :favorites

  has_attached_file :photo, :styles => { :small => "150x150>" },
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png', 'image/gif']
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :photos
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :tags
  has_many :photos, through: :tags
  has_many :favorites
  has_many :photos, through: :favorites
  has_many :photos


  validates_uniqueness_of :email

  has_attached_file :avatar, :styles => { :small => "150x150>" },
                  :url  => "/assets/products/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

  #validates_attachment_presence :avatar
  validates_attachment_size :avatar, :less_than => 5.megabytes
  validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @photo = @user.photos.find(params[:photo_id])
    @favorite = @photo.favorites.new
  end

  def create
    @user = User.find(params[:user_id])
    @photo = @user.photos.find(params[:photo_id])
    @favorite = @photo.favorites.new
    @favorite.user_id = @user.id
    if @favorite.save
      redirect_to user_photo_path(@user, @photo)
    else
      render 'new'
    end
  end

  private
  def favorites_params
    params.require(:favorite).permit(:user_id, :photo_id)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @photos = @user.photos
  end

  def new
    @user = User.find(params[:user_id])
    @photo = @user.photos.new
  end

  def create
    user = User.find(params[:user_id])
    @photo = user.photos.new(photo_params)
    if @photo.save
      redirect_to user_photos_path, notice: "Photo Added!"
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:user_id])
    @photo = @user.photos.find(params[:id])
  end

private
  def photo_params
    params.require(:photo).permit(:user_id, :description, :photo)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user), notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to new_user_path, notice: "Logged out!"
end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @photo = @user.photos.find(params[:photo_id])
    @tag = @photo.tags.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "Photo uploaded!"
    else
      render "edit", notice: "Upload failed"
    end
  end

private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoShare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Log Out", logout_path %>
  <% else %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for (@photo), url: user_photos_path, :html => { :multipart => true } do |f| %>

  <%= f.file_field :photo %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit("Add Photo", :class => "btn btn-primary") %>

<% end %>

app/views/photos/index.html.erb
<%= @user.email %>

<% @photos.each do |photo| %>
  <%= image_tag photo.photo.url %>
  <%= photo.description %>
<% end %>

app/views/photos/new.html.erb
<h1>Add a Photo</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<h1><%= @photo.description %></h1>

<%= image_tag @photo.photo.url %>

<h2>Tagged people:</h2>
<ul>
  <% @photo.tags.each do |tag| %>
  <% display = User.find(tag.user_id) %>
    <li><%= display.email %></li>
  <% end %>
</ul>

<p><%= link_to "Favorite", user_photo_favorites_path(@user, @photo),
                         :data => { :method => "create"},
                         :class => "btn btn-danger" %></p>

app/views/tags/_form.html.erb
<%= form_for (@tag), url: user_photo_tags_path(@user, @photo) do |f| %>

  <%= f.collection_select :user_id, User.all, :id, :email %>
  <%= f.submit("Add Tag", :class => "btn btn-primary") %>

<% end %>

app/views/tags/new.html.erb
<h1>Add Tag</h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for (@user), :html => { :multipart => true } do |f| %>

  <%= f.file_field :avatar %>

  <%= f.submit("Add Photo", :class => "btn btn-primary") %>

<% end %>

app/views/users/edit.html.erb
<h1> Add Profile Image </h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.email %>!</h1>

<% if @user.avatar_file_name == nil %>
  <%= link_to "Add profile photo", edit_user_path(@user) %>
  <% image_tag @user.avatar.url(:small) %>
<% else %>
  <%= image_tag @user.avatar.url(:small) %>
  <%= link_to "Edit profile photo", edit_user_path(@user) %>
<% end %>

<h2>Photos you are tagged in:</h2>
<ul>
  <% @user.tags.each do |tag| %>
    <% if tag.user_id == @user.id %>
      <%= image_tag Photo.find(tag.photo_id).photo.url %>
    <% end %>
  <% end %>
</ul>

<h2>Favorited Photos:</h2>
<ul>
  <% @user.favorites.each do |favorite| %>
    <% if favorite.user_id == @user.id %>
      <%= image_tag Photo.find(favorite.photo_id).photo.url %>
    <% end %>
  <% end %>
</ul>

<%= link_to "Add a new photo", new_user_photo_path(@user) %>